title: Peiqi Li's Homepage
page-top-title: Peiqi Li
top-section-bg-text: Mathematical Sciences
home-subtitle: Peiqi Li&ensp;|&ensp;李佩琦
copyright-text: '&copy; Peiqi Li 2023-2026. All Rights Reserved.'
